url: lifrancucci-portfolio.github.io
baseurl: /dynamics

title: DYNAMICS
email: info@dynamics.la
description: >- # this means to ignore newlines until "baseurl:"
  Dynamics es una consultora especializada en economía digital y sostenibilidad para América Latina.
  ---------------
  Dynamics is a consulting firm specializing in digital economy and sustainability in Latin America.
  
domain: www.dynamics.la       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://www.dynamics.la  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: ""    # place folder name if the site is served in a subfolder
permalink: pretty